[versions]
agp = "8.7.2"
kotlin = "2.0.21"
ksp = "2.0.21-1.0.25"
coreKtx = "1.15.0"
appcompat = "1.7.0"
activity = "1.9.3"
fragment = "1.8.5"
constraintlayout = "2.2.0"
liveCycle = "2.8.7"
viewPager2 = "1.1.0"
preference = "1.2.1"
roomKtx = "2.6.1"
work = "2.10.0"
googleAdmob = "23.5.0" # https://developers.google.com/admob/android/quick-start
unityAd = "4.12.1" # https://developers.google.com/admob/android/mediation/unity#step_3_import_the_unity_ads_sdk_and_adapter
startIo = "4.11.5" # https://support.start.io/hc/en-us/articles/360014774799-Integration-via-Maven
recyclerview = "1.3.2"
flexbox = "3.0.0"
material = "1.12.0"
gson = "2.10.1"
okhttp = "4.12.0"
retrofit = "2.11.0"
rxandroid3 = "3.0.2"
rxjava3 = "3.1.8"
chucker = "4.0.0"
glide = "4.16.0"
customactivityoncrash = "2.4.0"
circleimageview = "3.1.0"
koin = "3.5.6"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
hilt = "2.52"
emoji2 = "1.5.0"
deltadoxAndroid = "1.0.0"

# Compose Version
composePlugin = "1.7.0"
composeCompiler = "1.5.15" # https://developer.android.com/jetpack/androidx/releases/compose
composeAnimation = "1.6.7"# https://developer.android.com/jetpack/androidx/releases/compose
composeActivity = "1.9.3" # https://androidx.tech/artifacts/activity/activity-compose/
compose = "1.7.5" # https://developer.android.com/jetpack/androidx/releases/compose
composeMaterial = "1.7.5" # https://developer.android.com/jetpack/androidx/releases/compose
composeFoundation = "1.6.7" # https://developer.android.com/jetpack/androidx/releases/compose
composeMaterial3 = "1.3.1" # https://developer.android.com/jetpack/androidx/releases/compose
composeNavigation = "2.7.7" # https://androidx.tech/artifacts/navigation/navigation-compose/
composeHiltNavigation = "1.2.0"

[libraries]
# Android Kit
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
androidx-work-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }

# Android Kit
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "liveCycle" }

ads-google-admob = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "googleAdmob" }
ads-google-admob-lite = { group = "com.google.android.gms", name = "play-services-ads-lite", version.ref = "googleAdmob" }
ads-unityAd = { group = "com.unity3d.ads", name = "unity-ads", version.ref = "unityAd" }
ads-startIo = { group = "com.startapp", name = "inapp-sdk", version.ref = "startIo" }

androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "liveCycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "liveCycle" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "liveCycle" }
androidx-lifecycle-compiler = { group = "androidx.lifecycle", name = "lifecycle-compiler", version.ref = "liveCycle" }

androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewPager2" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
androidx-emoji2 = { group = "androidx.emoji2", name = "emoji2-bundled", version.ref = "emoji2"}

androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomKtx" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
androidx-room-rxjava3 = { group = "androidx.room", name = "room-rxjava3", version.ref = "roomKtx" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomKtx" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity"}
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "composeMaterial"}
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3"}
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "compose"}
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose"}
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose"}
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose"}
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose"}

androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }

google-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
google-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }

# --------------------------------------------------------------------------------------------------
# Test Library

androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

# --------------------------------------------------------------------------------------------------
# Library

square-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
square-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

square-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
square-retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
square-retrofit-adapter-rxjava3 = { group = "com.squareup.retrofit2", name = "adapter-rxjava3", version.ref = "retrofit" }

reactivex-rxjava3 = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava3" }
reactivex-rxandroid3 = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rxandroid3" }

github-chucker = { group = "com.github.chuckerteam.chucker", name = "library", version.ref = "chucker" }
github-glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
github-glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
github-customactivityoncrash = { group = "cat.ereza", name = "customactivityoncrash", version.ref = "customactivityoncrash" }
github-circleimageview =  { group = "de.hdodenhof", name = "circleimageview", version.ref = "circleimageview" }

koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-android-compat = { group = "io.insert-koin", name = "koin-android-compat", version.ref = "koin" }
koin-androidx-workmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager", version.ref = "koin" }

deltadox-android = { group = "com.github.deltadox", name = "deltadox-android", version.ref = "deltadoxAndroid" }

# --------------------------------------------------------------------------------------------------


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp"}
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "composePlugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
