[versions]
agp = "8.12.2"
kotlin = "2.2.10"
ksp = "2.2.10-2.0.2"
liveCycle = "2.9.3"

roomKtx = "2.7.2"
work = "2.10.3"
glideCompiler = "4.16.0"

hilt = "2.57.1"
emoji2 = "1.5.0"
frogoAndroid = "2.3.2"
frogoconsumeapi = "2.6.1"

[libraries]
androidx-work-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
androidx-lifecycle-compiler = { group = "androidx.lifecycle", name = "lifecycle-compiler", version.ref = "liveCycle" }
androidx-emoji2 = { group = "androidx.emoji2", name = "emoji2-bundled", version.ref = "emoji2"}
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomKtx" }

google-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
google-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

# --------------------------------------------------------------------------------------------------
github-glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glideCompiler" }
frogo-android = { group = "com.github.frogobox", name = "frogo-sdk", version.ref = "frogoAndroid" }
frogo-consume-api = { group = "com.github.frogobox", name = "frogo-consume-api", version.ref = "frogoconsumeapi" }
# --------------------------------------------------------------------------------------------------

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp"}
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
